### ISSUE TITLE
Will it support iOS5?

### ISSUE THREAD

**Issue by caiguo37** [zetachang/DCModalSegue#2]

**Comment by zetachang** [comment]
The current target on the CocoaPods is set to 6.0, but I think it's quite fine to use it in an iOS5 project (without the unwind segue part which is only supported in iOS 6.0). So you can just drop the classes into your iOS 5 project without using CocoaPods. And I will also lower down the supported target when releasing the next version. 

Thanks for addressing this. :smile:
