### ISSUE TITLE
Usage of DCModalViewController

### ISSUE THREAD

**Issue by alariccole** [zetachang/DCModalSegue#4]
Thanks for providing this example of taking a screenshot of a view for help in creating a modal segue. I'm not understanding the purpose of creating a new DCModalViewController, however. It seems to me that this kind of thing doesn't belong in the segue, so I'm wondering what the purpose of it is.

**Comment by zetachang** [comment]
I think the whole segue mechanism provided is to abstract the idea of view controller transition. And the purpose of creating a intermediate `DCModalViewController` is to have a place to coordinate the whole transition including adding the screenshot to its subviews. The most important part is that we need a place to hook up the dismiss method `- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^)(void))completion` to do the clean up and the _pushed forward_ animation.
