### ISSUE TITLE
iOS 7 Plans

### ISSUE THREAD

**Issue by sammio2** [zetachang/DCModalSegue#5]
I'm sure this is on the horizon.... But do you have any plans to update this to support iOS 7, currently the unwind segue isn't working properly!

**Comment by zetachang** [comment]
Hi, thank you for brining this up. 

I've tried out the demo project on Xcode-DP2, but it works fine as usual. Is there anything I missed?

**Comment by sammio2** [comment]
Ahh, you know what... I was being stupid! It's all working fine! Thanks for responding!

**Comment by zetachang** [comment]
Never mind, that's ok!  :wink:
