### ISSUE TITLE
Not support landscape iPad

### ISSUE THREAD

**Issue by kenpig** [zetachang/DCModalSegue#7]
Hi, DCModalSegue is great, But not support landscape iPad . Could you help me to fix that? Thank you.

**Comment by zetachang** [comment]
Hi, great to hear that!

Supporting iPad is definitely in future plan, but I currently don't have time to work on that. So if you are interested, feel free to dig into the code and send me a PR :rocket:

**Comment by kenpig** [comment]
Thanks for your help. I will send my project to you after dig into the code.

Best Regards

Kenpig

在 2013-9-8，下午2:35，David Chang notifications@github.com 写道：
